/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ChapterList`; params?: Router.UnknownInputParams; } | { pathname: `/SelectionPage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthBackground`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthScreenWrapper`; params?: Router.UnknownInputParams; } | { pathname: `/components/SelectionGroup`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ChapterList`; params?: Router.UnknownOutputParams; } | { pathname: `/SelectionPage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AuthBackground`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AuthForm`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AuthScreenWrapper`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SelectionGroup`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/ChapterList${`?${string}` | `#${string}` | ''}` | `/SelectionPage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `/components/AuthBackground${`?${string}` | `#${string}` | ''}` | `/components/AuthForm${`?${string}` | `#${string}` | ''}` | `/components/AuthScreenWrapper${`?${string}` | `#${string}` | ''}` | `/components/SelectionGroup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ChapterList`; params?: Router.UnknownInputParams; } | { pathname: `/SelectionPage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthBackground`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthScreenWrapper`; params?: Router.UnknownInputParams; } | { pathname: `/components/SelectionGroup`; params?: Router.UnknownInputParams; };
    }
  }
}
